### PR TITLE
Updated install instructions

### PR DESCRIPTION
**Pull request by unixorn**
* Added install instructions for [Antigen](https://github.com/zsh-users/antigen) and [zgen](https://github.com/tarjoilija/zgen)
* Edited [oh-my-zsh](github.com/robbyrussell/oh-my-zsh) install instructions

### CODE REVIEW

**Comment by jdubois** [comment]
Thanks! I've never heard of those, and they look handy: I've looked for making a PR to the official oh-my-zsh repo, but it has a very low activity. So having an alternative is very good.
However, I'd like to keep the oh-my-zsh section first, as it's the one everybody knows and expects.

**Comment by unixorn** [comment]
Ok, I'll move it. I was doing them in alphabetical order.

**Comment by unixorn** [comment]
[Antigen](https://github.com/zsh-users/antigen) and [Zgen](https://github.com/tarjoilija/zgen) both start up considerably faster than [omz](https://github.com/jhipster/jhipster-oh-my-zsh-plugin/pull/github.com/robbyrussell/oh-my-zsh) and can use both 3rd party omz compatible plugins and the ones built into omz. They'll both take care of automagically cloning plugins from standalone git repos and can both also keep those plugins up to date for you.

Of all the frameworks I've looked at, I'm currently using zgen since it only calculates your plugin list once, when you change it, rather than every time you start a new terminal session like antigen does.

**Comment by jdubois** [comment]
Thanks a lot!!!
This plugin is still a little bit "hidden", until we have enough feedback, but it should soon become very popular.

**Comment by unixorn** [comment]
I added it to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) so it is discoverable.

**Comment by jdubois** [comment]
Thanks!

**Pull request merged**
