### PR TITLE
Add alias jh to use jhipster cli

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Following this commit https://github.com/jhipster/generator-jhipster/commit/dad7257e4bb4750ebad6e740c820eb378bc04143, add back the `jh` alias to use directly `jhipster`

### CODE REVIEW

**Comment by ruddell** [comment]
Does this work?  I can't run just `jhipster`

**Comment by pascalgrimaud** [comment]
@ruddell : `jhipster` doesn't work for you?
On my machine, `jh` -> `jhipster` -> `yo jhipster`

**Comment by ruddell** [comment]
@pascalgrimaud My fault, it works now.  I didn't realize `jhipster` now runs the projects as well as `jh`

**Comment by deepu105** [comment]
I think all the alias can use the cli instead of yeoman commands

**Comment by pascalgrimaud** [comment]
Sure @deepu105 !
But it was coded very quickly in the train, to not break the usual `jh` :smile: 

I agree, all the other aliases should be updated to use jhipster -> I will do it later

**Comment by deepu105** [comment]
ok :)

**Comment by pascalgrimaud** [comment]
Just updated this PR.

@atomfrede : if I copy/paste this same file into https://github.com/jhipster/jhipster-fisherman-plugin, does it work? As there are minor difference, so I'm not sure and I was able to test it.
If you can't test, I will try in a specific jhipster-devbox to avoid conflict with zsh

**Comment by atomfrede** [comment]
@pascalgrimaud Most things should work, but the functions must be changed. I can take care of that for the fisherman plugin and start a new PR for that.

**Comment by pascalgrimaud** [comment]
Ok I see. I let you do the PR for fishman as you can test. Thanks @atomfrede !

**Comment by atomfrede** [comment]
@pascalgrimaud My pr is ready: https://github.com/jhipster/jhipster-fisherman-plugin/pull/5

**Comment by pascalgrimaud** [comment]
thanks @atomfrede, I closed my other PR

**Comment by pascalgrimaud** [comment]
Let's merge this, as jhipster-cli has been released!

**Pull request merged**
